### ISSUE TITLE
Unable to build the library

### ISSUE THREAD

**Issue by ehamzic1** [dwu4/genome-privacy#1]
Hi all!
The issue I am experiencing is that after cloning the repository and trying to build it by running `./build_libs.sh`, I get a large output containing code-related errors. My assumption is that this happens because of the OS or compiler incompatibilities. Any experiences with this? I am running Linux Mint 19 and tried also on Ubuntu 18.04., but also to no avail. 
Here is one part of the error list:
![Screenshot](https://user-images.githubusercontent.com/30796767/78898364-f5176400-7a73-11ea-8e9a-ca88394b4d9e.png)

**Comment by dwu4** [comment]
It looks like you are missing OpenSSL.
